name: Build Ghost and test theme

on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run:  pnpm add gscan
      - name: check if zip avaiable or not
        run: |
            if ! [ -x "$(command -v zip)" ]; then
               echo "installing zip command"
               apt-get install zip -y
            fi
      - run: ls -la
      - run: pwd
    #   - run : zip fastest.zip assets/build/*/*  partials/*/* author.hbs default.hbs error.hbs index.hbs page.hbs post.hbs tag.hbs
    #   - run: pnpm run gscan fastest.zip