name: Build Ghost and test theme

on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run:  pnpm add gscan
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1.2
        with:
            files: assets/build/ partials/ author.hbs default.hbs error.hbs index.hbs page.hbs post.hbs tag.hbs
            dest: ${{ github.workspace }}/fastest.zip
      - run: pnpm gscan -z ${{ github.workspace }}/fastest.zip